// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxFcLG35XPHrSn1nxB2Qr8VM9jdC0SsKY',
    appId: '1:390427294036:web:d7c4137bd4ec09b249b0c1',
    messagingSenderId: '390427294036',
    projectId: 'corso-flutter-9d16a',
    authDomain: 'corso-flutter-9d16a.firebaseapp.com',
    storageBucket: 'corso-flutter-9d16a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlw5SbZWynr012qgxxqzeSwELWNEjh7BE',
    appId: '1:390427294036:android:06339d65badb856849b0c1',
    messagingSenderId: '390427294036',
    projectId: 'corso-flutter-9d16a',
    storageBucket: 'corso-flutter-9d16a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_qXyhW-pVwlNoNPvAKu3J538JqlfpGCE',
    appId: '1:390427294036:ios:5dfbaf8b344737a149b0c1',
    messagingSenderId: '390427294036',
    projectId: 'corso-flutter-9d16a',
    storageBucket: 'corso-flutter-9d16a.firebasestorage.app',
    iosBundleId: 'me.gattoprogrammatore.corsoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_qXyhW-pVwlNoNPvAKu3J538JqlfpGCE',
    appId: '1:390427294036:ios:9ad4bef32ad9eda849b0c1',
    messagingSenderId: '390427294036',
    projectId: 'corso-flutter-9d16a',
    storageBucket: 'corso-flutter-9d16a.firebasestorage.app',
    iosBundleId: 'com.gatto-programmatore.tutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxFcLG35XPHrSn1nxB2Qr8VM9jdC0SsKY',
    appId: '1:390427294036:web:a0ddc0646d4ee12e49b0c1',
    messagingSenderId: '390427294036',
    projectId: 'corso-flutter-9d16a',
    authDomain: 'corso-flutter-9d16a.firebaseapp.com',
    storageBucket: 'corso-flutter-9d16a.firebasestorage.app',
  );
}
